default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_App_development
  username: postgres
  # password: jheart1998.
  password: 1234

test:
  <<: *default
  database: Blog_App_test
  username: postgres
  # password: jheart1998.
  password: 1234

production:
  <<: *default
  database: Blog_App_production
  username: postgres
  # password: jheart1998.
  password: 1234
